### ISSUE TITLE
一些前排弹幕仍然无法屏蔽

### ISSUE THREAD

**Issue by Youwenqwq** [Mark9804/bilibili-danmaku-regex#1]
如下图所示
![Annotation 2020-03-19 170712.png](https://i.loli.net/2020/03/19/tvKlb5wMzVs8u3c.png)
![Annotation 2020-03-19 170738.png](https://i.loli.net/2020/03/19/9YMnU3sH8R5Dayr.png)
主要是个人认为,结合那个插件并无必要,于是直接复制到了Bilibili正则表达式里,但是发现不起作用,想来询问一下,能提供支持的话最好,不能的话也没事,毕竟我并没有安装那个插件

**Comment by mark9804** [comment]
你好。

经过确认，以上正则确实没有包括截图中的情况。经过修正后的正则如下：

```
^[第前钱]([0-9零一二两三四五六七八九十百千万萬亿①②③④⑤⑥⑦⑧⑨⑩几].{0,6})?$|[第前][0-9零一二两三四五六七八九十百千万萬亿①②③④⑤⑥⑦⑧⑨⑩]
^.{1,6}[天时点分钟秒][前钱]
^我?超前~{0,}$|^我?好快$|好早|(打架|大家)早|^前排
^趁热|^热的|^(还是?)热[乎热]|^热乎的?.?|^烫[手嘴]|^好?烫{1,}
```

网友的创造力是无穷的，我会尽量屏蔽我能想到（或者已经见到）的弹幕组合，但是一定还会有漏网的现象。感谢提供的截图反馈。

**Comment by Youwenqwq** [comment]
嗯嗯,谢谢改进(*≧︶≦)
